Add and Remove Items from To-Do-List
ginabeki/to-do-list pull request #2
Opened 2022-11-02 20:00 UTC by ginabeki

The following was performed in this task;
- Removed all hardcoded items from the tasks array.
- Created new JavaScript files for the new functionality.
- Implemented a function for adding a new task (add a new element to the array).
- Implement a function for deleting a task (remove an element from the array).
- Implement a function for editing task descriptions.
- Have the property completed set to false and the property index set to the value of the new array length.
- Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique.
- All changes to the To Do List should be saved in local storage.

2022-11-02 20:44 UTC, cynthiainga requested changes
Hi @ginabeki, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit history ✔️ 
- [ ] Correct Gitflow ✔️ 

## Required Changes ♻️

- [x] Please kindly check the comments under the review 👇👇

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 20:44 UTC, cynthiainga commented on src/edit-remove.js
> +  data.map(i => i.index = count += 1); // eslint-disable-line
- [ ]  Please kindly do not disable linters, fix linters errors helps programmers to write clean and clear codebase 😁 😉

2022-11-02 20:44 UTC, cynthiainga commented on src/index.js
> +import { getFromLocal, updateLocalStorage } from './local-storage';// eslint-disable-line
- [ ] Please kindly do not disable linters, fix linters errors helps programmers to write clean and clear codebase 😁 😉

2022-11-02 20:44 UTC, cynthiainga commented on src/index.js
> +// eslint-disable-next-line import/prefer-default-export
- [ ] Please kindly do not disable linters, fix linters errors helps programmers to write clean and clear codebase 😁 😉

2022-11-02 20:44 UTC, cynthiainga commented on src/index.js
> +  data.map(i.index = count += 1); // eslint-disable-line
- [ ] Please kindly do not disable linters, fix linters errors helps programmers to write clean and clear codebase 😁 😉

2022-11-02 20:44 UTC, cynthiainga commented on src/local-storage.js
> +import { myArray } from './index';// eslint-disable-line
- [ ] Please kindly do not disable linters, fix linters errors helps programmers to write clean and clear codebase 😁 😉

2022-11-02 20:44 UTC, cynthiainga commented on src/local-storage.js
> +  data.map(i => {// eslint-disable-line
- [ ] Please kindly do not disable linters, fix linters errors helps programmers to write clean and clear codebase 😁 😉

2022-11-02 20:44 UTC, cynthiainga commented on src/local-storage.js
> +      updateLocalStorage();// eslint-disable-line
- [ ] Please kindly do not disable linters, fix linters errors helps programmers to write clean and clear codebase 😁 😉

2022-11-02 20:44 UTC, cynthiainga commented on src/index.js
> +    // e.preventDefault();
- [ ] I think it would be better if you delete this commented line of code to have a clean codebase 😎😎

2022-11-02 20:44 UTC, cynthiainga commented on src/index.js
> +  });
- [ ] As required the property `index` is set to the value of the new array length (i.e. if a 1rst task is added to the list, the index of that task should equal to 1, or if a 3rd task is added to the list, the index of that task should equal to 3 ) but is not the case for you, the index starts by 0,1,2,... Please kindly fix that 🙃 😉

<img width="434" alt="Screen Shot 2022-11-02 at 22 15 22" src="https://user-images.githubusercontent.com/74501523/199598463-d824c415-cde7-4213-b53f-f29c4193f4d1.png">

2022-11-03 11:24 UTC, Tadesse-Alemayehu requested changes
### Hi @ginabeki 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![giphy (1)](https://user-images.githubusercontent.com/69077061/199708867-b87784aa-7cef-4979-addd-f9b78e994bf3.gif)


 ## Highlights
 - [ ] Good job making most of the changes requested by the previous reviewer. 
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 11:24 UTC, TadesseDev commented on src/index.js
> +  }
- [ ] Dear @ginabeki, You have done an incredible job implementing most of the features. As the previous reviewer mentioned for the index we need to assign the appropriate number. the first task should have `index=1`, the second task should have `index=2`, and so on.
- [Optional] Also, deleting a task should update all remaining items' indexes, so they represent the current list order and are unique. This is only optional since It has not been mentioned to you before. 

## I have attached a video to help you explain the issue.

https://user-images.githubusercontent.com/69077061/199698740-345f9b31-18fd-4652-b574-7585334ac5a8.mp4

2022-11-03 19:39 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Gina, 
## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
README is professional. :heavy_check_mark:
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-03 20:11 UTC, merged